import type {NextPage,} from 'next'
import Head from 'next/head'
import React from 'react'
import ThemeChanger from '../../components/ThemeChanger'
import GoBack from '../../components/GoBack'
import Header from '../../layout/Header'

const Settings: NextPage = () => {
	return (
		<div>
			<Head>
				<title>FeedBack | Settings</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/public/favicon.ico"/>
			</Head>
			<Header>
				<GoBack/>
				<ThemeChanger/>
			</Header>
		</div>
	)
}


export default Settings
