import type {NextPage,} from 'next'
import Head from 'next/head'
import Avatar from '../components/Avatar'
import Header from '../layout/Header'
import IconButton from '../components/UI/IconButton'
import Title from '../components/UI/Title'
import {useRouter,} from 'next/router'
import {Routes,} from '../constants/routes'
import DialogList from '../components/DialogList'
import Link from 'next/link'
import SearchIcon from '../../public/assets/icons/search.svg'

const Home: NextPage = () => {
	const router = useRouter()

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/public/favicon.ico"/>
			</Head>
			<Header>
				<IconButton onClick={() => router.push(Routes.SEARCH)} Icon={SearchIcon}/>
				<Title>Home</Title>
				<Link href={Routes.PROFILE + '62daa8e66b818b9f9349cc2a'}>
					<a>
						<Avatar fullName={'Vladislav Kravchuk'}
								avatarUrl={'https://images.unsplash.com/photo-1657264533870-187e6a18ac42?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'}/>
					</a>
				</Link>
			</Header>
			<DialogList/>
		</div>
	)
}

export default Home
