import type {NextPage,} from 'next'
import Head from 'next/head'
import Header from '../layout/Header'
import IconButton from '../components/UI/IconButton'
import Title from '../components/UI/Title'
import {useRouter,} from 'next/router'
import {Routes,} from '../constants/routes'
import DialogList from '../components/DialogList'
import SearchIcon from '../../public/assets/icons/search.svg'
import MyAvatar from '../components/MyAvatar'
import React from 'react'

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/public/favicon.ico"/>
			</Head>
			<HomeHeader/>
			<DialogList/>
		</div>
	)
}

const HomeHeader: React.FC = () => {
	const router = useRouter()

	return <Header>
		<IconButton onClick={() => router.push(Routes.SEARCH)} Icon={SearchIcon}/>
		<Title>Home</Title>
		<MyAvatar/>
	</Header>
}

export default Home
