import type {NextPage} from 'next';
import Head from 'next/head';
import Avatar from '../components/Avatar';
import Header from '../layout/Header';
import IconButton from '../components/IconButton';
import DialogItemLoader from '../components/loaders/DialogItemLoader';
import Title from '../components/Title';
import {useRouter} from 'next/router';
import React from 'react';
import {useAppSelector} from '../store/hooks';
import {selectSearchData, selectSearchLoadingState} from '../store/slices/search';
import {LoadingState} from '../store/types';
import SearchUserItem from '../components/SearchUserItem';
import SearchUserInput from '../components/SearchUserInput';

const Search: NextPage = () => {
	const router = useRouter();
	const loadingState = useAppSelector(selectSearchLoadingState);
	const searchData = useAppSelector(selectSearchData);

	return (
		<div>
			<Head>
				<title>FeedBack | Search</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/public/favicon.ico"/>
			</Head>
			<Header>
				<IconButton onClick={() => router.back()} iconPath="/assets/icons/back.svg"/>
				<Title>Search</Title>
				<Avatar path="/auth/register" fullName={'Vladislav Kravchuk'}
						avatarUrl={'https://images.unsplash.com/photo-1657264533870-187e6a18ac42?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'}/>
			</Header>
			<div className="m-3.5">
				<SearchUserInput/>
			</div>
			{loadingState === LoadingState.LOADED && searchData && searchData.map(item => (
				<SearchUserItem key={item._id} _id={item._id} email={item.email} fullName={item.fullName}/>
			))}
			{
				loadingState === LoadingState.LOADING && (
					new Array(5).fill(null).map((_, idx) => <DialogItemLoader key={idx}/>)
				)
			}
		</div>
	);
};

export default Search;
