import type {NextPage,} from 'next'
import Head from 'next/head'
import React from 'react'
import SearchUserInput from '../components/SearchUserInput'
import {UserAPI,} from '../store/services/UserService'
import DialogItemLoader from '../components/loaders/DialogItemLoader'
import Empty from '../components/Empty'
import SearchUserItems from '../components/SearchUserItems'
import Header from '../layout/Header'
import Title from '../components/UI/Title'
import Link from 'next/link'
import Avatar from '../components/Avatar'
import {Routes,} from '../constants/routes'
import GoBack from '../components/GoBack'

const Search: NextPage = () => {
	return <div>
		<Head>
			<title>FeedBack | Search</title>
			<meta name="description" content="Generated by create next app"/>
			<link rel="icon" href="/public/favicon.ico"/>
		</Head>
		<Header>
			<GoBack/>
			<Title>Search</Title>
			<Link href={Routes.SETTINGS}>
				<a>
					<Avatar fullName={'Vladislav Kravchuk'}
							avatarUrl={'https://images.unsplash.com/photo-1657264533870-187e6a18ac42?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80'}/>
				</a>
			</Link>
		</Header>
		<SearchContent/>
	</div>
}


const SearchContent = () => {
	const [search, {data, isLoading,},] = UserAPI.useSearchMutation()

	const handleSearch = React.useCallback((query: string) => {
		search(query)
	}, [search,])

	return <div className="m-3.5">
		<SearchUserInput onSearch={handleSearch}/>
		{isLoading && <div>
            <DialogItemLoader/>
            <DialogItemLoader/>
            <DialogItemLoader/>
            <DialogItemLoader/>

        </div>}
		{data && !data.length && <Empty/>}
		{data && !!data.length && <SearchUserItems data={data}/>}
	</div>
}

export default Search
