import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Avatar from "../components/Avatar";
import Header from '../layout/Header';
import IconButton from "../components/IconButton";
import DialogItem from "../components/DialogItem";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header>
                <IconButton iconPath="/assets/icons/search.svg"/>
                <h3>Home</h3>
                <Avatar path="/auth/register" fullName={"Vladislav Kravchuk"}
                        avatarUrl={"https://images.unsplash.com/photo-1657264533870-187e6a18ac42?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"}/>
            </Header>
            <DialogItem _id={"123k21m1123ouawe"}
                        lastMessageText={"Loreinguincuincludinguincludinguincludinguincludingversions of Lorem Ipsum."}
                        lastMessageTime={new Date()} fullName={"Vladislav Kravchuk"}/>
            <DialogItem _id={"123k21m1123ouawe"}
                        lastMessageText={"Hello 📬"}
                        avatarUrl={"https://images.unsplash.com/photo-1657264533870-187e6a18ac42?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"}
                        lastMessageTime={new Date()} fullName={"Vladislav Kravchuk"}/>
        </div>
    )
}

export default Home
